-- MySQL Script generated by MySQL Workbench
-- 05/16/18 19:10:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`hello_world`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`hello_world` ;

CREATE TABLE IF NOT EXISTS `test`.`hello_world` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL COMMENT '名称',
  `phone` VARCHAR(255) NULL COMMENT '手机号',
  `type` TINYINT NULL DEFAULT 0 COMMENT 'helloworld类型，测试枚举类',
  `sex` TINYINT NULL DEFAULT 0 COMMENT '性别枚举 0女 1男 2未知',
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '示例对象表格';


-- -----------------------------------------------------
-- Table `test`.`sys_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`sys_permission` ;

CREATE TABLE IF NOT EXISTS `test`.`sys_permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `available` BIT(1) NOT NULL DEFAULT b'1',
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '系统权限';


-- -----------------------------------------------------
-- Table `test`.`sys_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`sys_role` ;

CREATE TABLE IF NOT EXISTS `test`.`sys_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `available` BIT(1) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `level` INT(11) NOT NULL DEFAULT 0 ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '系统角色';


-- -----------------------------------------------------
-- Table `test`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`user_info` ;

CREATE TABLE IF NOT EXISTS `test`.`user_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_nickname` VARCHAR(255) NOT NULL COMMENT '用户昵称',
  `user_avatar` VARCHAR(255) NULL COMMENT '用户头像',
  `user_sex` TINYINT NULL COMMENT '性别 0女 1男 2保密 等等。。',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `test`.`user_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`user_auth` ;

CREATE TABLE IF NOT EXISTS `test`.`user_auth` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_info_id` BIGINT(20) NOT NULL COMMENT '关联用户信息',
  `auth_available` BIT(1) NOT NULL DEFAULT b'1' COMMENT '是否可用',
  `login_type` VARCHAR(255) NOT NULL DEFAULT 'username' COMMENT '账号类型，用户名密码',
  `login_account` VARCHAR(255) NOT NULL COMMENT '登录账号',
  `login_password` VARCHAR(255) NOT NULL COMMENT '密码',
  `login_salt` VARCHAR(255) NULL DEFAULT '' COMMENT '密码加盐',
  `last_login_ip` VARCHAR(45) NULL DEFAULT '0.0.0.0' COMMENT '最后登录ip地址',
  `last_login_time` DATETIME NULL COMMENT '最后登录时间',
  `last_login_device` VARCHAR(45) NULL COMMENT '最后登录的设备',
  `last_login_try_ip` VARCHAR(45) NULL DEFAULT '0.0.0.0',
  `last_login_try_count` INT NULL DEFAULT 0 COMMENT '最后一次登录尝试',
  `last_login_token` VARCHAR(255) NULL COMMENT '上次登录生成的token',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_auth_user_info1_idx` (`user_info_id` ASC),
  CONSTRAINT `fk_user_auth_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `test`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户登录账号表';


-- -----------------------------------------------------
-- Table `test`.`sys_permission_has_sys_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`sys_permission_has_sys_role` ;

CREATE TABLE IF NOT EXISTS `test`.`sys_permission_has_sys_role` (
  `sys_permission_id` BIGINT(20) NOT NULL,
  `sys_role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`sys_permission_id`, `sys_role_id`),
  INDEX `fk_sys_permission_has_sys_role_sys_role1_idx` (`sys_role_id` ASC),
  INDEX `fk_sys_permission_has_sys_role_sys_permission_idx` (`sys_permission_id` ASC),
  CONSTRAINT `fk_sys_permission_has_sys_role_sys_permission`
    FOREIGN KEY (`sys_permission_id`)
    REFERENCES `test`.`sys_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_permission_has_sys_role_sys_role1`
    FOREIGN KEY (`sys_role_id`)
    REFERENCES `test`.`sys_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '角色权限多对多关联表';


-- -----------------------------------------------------
-- Table `test`.`user_info_has_sys_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`user_info_has_sys_role` ;

CREATE TABLE IF NOT EXISTS `test`.`user_info_has_sys_role` (
  `user_info_id` BIGINT(20) NOT NULL,
  `sys_role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_info_id`, `sys_role_id`),
  INDEX `fk_user_info_has_sys_role_sys_role1_idx` (`sys_role_id` ASC),
  INDEX `fk_user_info_has_sys_role_user_info1_idx` (`user_info_id` ASC),
  CONSTRAINT `fk_user_info_has_sys_role_user_info1`
    FOREIGN KEY (`user_info_id`)
    REFERENCES `test`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_info_has_sys_role_sys_role1`
    FOREIGN KEY (`sys_role_id`)
    REFERENCES `test`.`sys_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户角色多对多关联表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
